[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://flo-1m00.onrender.com/api"

# Enable Next.js SSR Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"
