# Generated by Django 5.0.1 on 2025-10-09 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About  floneo', max_length=200)),
                ('description', models.TextField(default='We help businesses automate their processes')),
                ('content', models.TextField(default='Detailed about content goes here')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='More than Automation', max_length=200)),
                ('subtitle', models.CharField(default='Our Analytics Feature', max_length=100)),
                ('description', models.TextField(default='Turn Insights Into Savings')),
                ('content', models.TextField(default='Our advanced analytics tools provide you with clear, actionable insights...')),
                ('savings_amount', models.CharField(default='$500+', max_length=20)),
            ],
            options={
                'verbose_name': 'Analytics Section',
                'verbose_name_plural': 'Analytics Section',
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='zap', help_text="Lucide icon name (e.g., 'zap', 'bar-chart-3', 'clock', 'shield')", max_length=50)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Feature Card',
                'verbose_name_plural': 'Feature Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Build. Automate. Scale.', max_length=100)),
                ('copyright_text', models.CharField(default='© 2025  floneo. All rights reserved.', max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Build. Automate. Scale.', max_length=100)),
                ('title', models.CharField(default='Low-Code/No-Code Platform', max_length=200)),
                ('description', models.TextField(default='Turn manual processes into instant, powerful applications')),
                ('cta_primary_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_secondary_text', models.CharField(default='Watch Demo', max_length=50)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='MetricBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g., '85', '2.5', '500'", max_length=10)),
                ('suffix', models.CharField(default='%', help_text="e.g., '%', 'K', 'M', 'x'", max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='blue', help_text='CSS color class or hex code', max_length=50)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Metric Box',
                'verbose_name_plural': 'Metric Boxes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('href', models.CharField(help_text="URL or anchor link (e.g., '#features', '/about')", max_length=100)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('color', models.CharField(default='blue', help_text='CSS color class or hex code', max_length=50)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(max_length=100)),
                ('author_company', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'id'],
            },
        ),
    ]
