# Generated by Django 5.0.1 on 2025-10-10 01:15

import ckeditor.fields
import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form Submission',
                'verbose_name_plural': 'Contact Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(default='Get in Touch', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Contact Us', max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, default="We'd love to hear from you")),
                ('email', models.EmailField(default='contact@ floneo.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20)),
                ('address', models.TextField(blank=True, default='123 Business St, City, State 12345')),
                ('form_title', models.CharField(default='Send us a message', max_length=100)),
                ('form_submit_text', models.CharField(default='Send Message', max_length=50)),
                ('form_success_message', models.TextField(default="Thank you! We'll get back to you soon.")),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='EnhancedFooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('company_name', models.CharField(default=' floneo', max_length=100)),
                ('tagline', models.CharField(default='Build. Automate. Scale.', max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Empowering businesses with automation')),
                ('privacy_policy_text', models.CharField(default='Privacy Policy', max_length=50)),
                ('privacy_policy_url', models.CharField(default='/privacy', max_length=200)),
                ('terms_conditions_text', models.CharField(default='Terms and Conditions', max_length=50)),
                ('terms_conditions_url', models.CharField(default='/terms', max_length=200)),
                ('copyright_text', models.CharField(default='© 2025  floneo. All rights reserved.', max_length=200)),
                ('show_made_in_framer', models.BooleanField(default=True, help_text="Show 'Made in Framer' attribution")),
                ('background_color', colorfield.fields.ColorField(default='#F5F5F5', help_text='Background color for the section', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#000000', help_text='Text color for the section', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enhanced Footer Section',
                'verbose_name_plural': 'Enhanced Footer Section',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor.fields.RichTextField()),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(default='Frequently Asked Questions', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Help Center', max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Find answers to common questions')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_period', models.CharField(default='month', help_text="e.g., 'month', 'year'", max_length=20)),
                ('description', models.TextField()),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as most popular plan')),
                ('cta_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_url', models.CharField(default='#', max_length=200)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(default='Choose Your Plan', max_length=200)),
                ('subtitle', models.CharField(default='Flexible pricing for every business', max_length=100)),
                ('description', ckeditor.fields.RichTextField(default='Select the perfect plan for your needs')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Section',
                'verbose_name_plural': 'Pricing Section',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=' floneo', max_length=100)),
                ('site_description', models.TextField(default='Low-Code/No-Code Platform for Business Automation')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('meta_title', models.CharField(default=' floneo - Business Automation Platform', max_length=60)),
                ('meta_description', models.CharField(default='Transform your business with our low-code automation platform', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, default='automation, low-code, business, platform', max_length=200)),
                ('primary_email', models.EmailField(default='contact@ floneo.com', max_length=254)),
                ('primary_phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default="We're currently updating our site. Please check back soon!")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('slack', 'Slack'), ('threads', 'Threads'), ('other', 'Other')], max_length=20)),
                ('platform_name', models.CharField(help_text="Display name (e.g., 'Follow us on Twitter')", max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(default='fab fa-facebook', help_text='CSS icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(blank=True, default='Connect With Us', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Follow us on social media', max_length=100)),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Section',
                'verbose_name_plural': 'Social Media Section',
            },
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_primary_url',
            field=models.CharField(default='#', help_text='URL for primary CTA', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_secondary_url',
            field=models.CharField(default='#', help_text='URL for secondary CTA', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show/hide this section'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='herosection',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Text color for the section', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herosection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=ckeditor.fields.RichTextField(default='Turn manual processes into instant, powerful applications'),
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
