# Generated by Django 5.0.1 on 2025-10-10 03:21

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_abouttabletsection_aipoweredanalyticssection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(default='More than', max_length=200)),
                ('subtitle', models.CharField(default='Automation', max_length=200)),
                ('description', ckeditor.fields.RichTextField(default=" floneo isn't just about managing processes — it's about automating and scaling the workflows that fuel your business.")),
                ('cta_primary_text', models.CharField(default='Get Started', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Learn More', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/about', max_length=200)),
                ('background_color', models.CharField(default='linear-gradient(135deg, #a8e6cf 0%, #88d8a3 100%)', help_text='CSS background (color, gradient, etc.)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benefits Section',
                'verbose_name_plural': 'Benefits Section',
            },
        ),
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🔒', help_text='Emoji icon for the benefit', max_length=10)),
                ('position', models.CharField(choices=[('top-center', 'Top Center'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('middle-left', 'Middle Left'), ('middle-right', 'Middle Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right'), ('bottom-center', 'Bottom Center')], default='top-center', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='content.benefitssection')),
            ],
            options={
                'verbose_name': 'Benefit Item',
                'verbose_name_plural': 'Benefit Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
