# Generated by Django 5.0.1 on 2025-10-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_benefitssection_benefititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitssection',
            name='background_color',
            field=models.CharField(default='radial-gradient(circle at center, #2ECC71 0%, #27AE60 30%, #1E8449 60%, #0F4C2C 100%)', help_text='CSS background (color, gradient, etc.)', max_length=200),
        ),
    ]
