# Generated by Django 5.0.1 on 2025-10-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_update_benefits_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitssection',
            name='background_color',
            field=models.CharField(default='radial-gradient(circle at center, #a8e6cf 0%, #c8f2d4 40%, #e8f8ed 70%, #f8fdf9 100%)', help_text='CSS background (color, gradient, etc.)', max_length=200),
        ),
    ]
