# Generated by Django 5.0.1 on 2025-10-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_update_benefits_light_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectingexcellencesection',
            options={'verbose_name': 'About Us Section', 'verbose_name_plural': 'About Us Section'},
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='badge_text',
            field=models.CharField(default='ABOUT US', max_length=50),
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='title',
            field=models.CharField(default='About Us', max_length=200),
        ),
    ]
