# Generated by Django 5.0.1 on 2025-10-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_update_about_us_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectingexcellencesection',
            options={'verbose_name': 'Architecting Excellence Section', 'verbose_name_plural': 'Architecting Excellence Section'},
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='badge_text',
            field=models.CharField(default='WHY CHOOSE US', max_length=50),
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='title',
            field=models.CharField(default='Architecting Excellence', max_length=200),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Chat message text')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='user', max_length=10)),
                ('order', models.IntegerField(default=1, help_text='Order of message in conversation')),
                ('delay', models.FloatField(default=0, help_text='Animation delay in seconds')),
                ('human_touch_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='content.humantouchsection')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['order'],
            },
        ),
    ]
