# Generated by Django 5.0.1 on 2025-10-10 05:42

import ckeditor.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_chat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this section')),
                ('order', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('badge_text', models.CharField(default='WHY CHOOSE US', max_length=50)),
                ('title', models.CharField(default='Why Choose Us', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='that puts you in charge of your operations without IT bottlenecks', max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Experience unparalleled quality and innovation')),
                ('stat_1_value', models.CharField(default='75', max_length=10)),
                ('stat_1_label', models.CharField(default='spending habits', max_length=50)),
                ('stat_2_value', models.CharField(default='60', max_length=10)),
                ('stat_2_label', models.CharField(default='cost reductions', max_length=50)),
                ('stat_3_value', models.CharField(default='45', max_length=10)),
                ('stat_3_label', models.CharField(default='efficiency gains', max_length=50)),
                ('global_title', models.CharField(default='Global Reach', max_length=100)),
                ('global_description', models.TextField(default='Our app supports users in over 140 countries, offering global tools to manage and optimize your finances.')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
        migrations.AlterModelOptions(
            name='architectingexcellencesection',
            options={'verbose_name': 'About Us Section', 'verbose_name_plural': 'About Us Section'},
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='badge_text',
            field=models.CharField(default='ABOUT US', max_length=50),
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='title',
            field=models.CharField(default='About Us', max_length=200),
        ),
    ]
