# Generated by Django 5.0.1 on 2025-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_separate_why_choose_us_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='global_description',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='global_title',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='stat_1_label',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='stat_1_value',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='stat_2_label',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='stat_2_value',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='stat_3_label',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='stat_3_value',
        ),
        migrations.RemoveField(
            model_name='architectingexcellencesection',
            name='title',
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='counter_1_label',
            field=models.CharField(default='Process Efficiency', help_text='Label for first counter', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='counter_1_value',
            field=models.IntegerField(default=70, help_text='First percentage counter (e.g., 70 for 70%)'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='counter_2_label',
            field=models.CharField(default='Automation Success', help_text='Label for second counter', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='counter_2_value',
            field=models.IntegerField(default=85, help_text='Second percentage counter (e.g., 85 for 85%)'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='main_title_line1',
            field=models.CharField(default='Architecting', help_text='First line of main title', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='main_title_line2',
            field=models.CharField(default='Excellence', help_text='Second line of main title', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='philosophy_button_text',
            field=models.CharField(default='View Services', max_length=50),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='philosophy_button_url',
            field=models.CharField(default='#', help_text='URL for philosophy card button', max_length=200),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='philosophy_title',
            field=models.TextField(default='OUR philosophy is simple: workflow creation must be visual, instant, and effortlessly scalable, empowering you to build the future of your operations—fast.', help_text='Philosophy card main text'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_1_description',
            field=models.TextField(default='Build workflows visually with our intuitive drag-and-drop interface', help_text='Step 1 description'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_1_title',
            field=models.CharField(default='Drag & Drop', help_text='Step 1 title', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_2_description',
            field=models.TextField(default='Seamlessly integrate with your existing tools and systems', help_text='Step 2 description'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_2_title',
            field=models.CharField(default='Connect', help_text='Step 2 title', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_3_description',
            field=models.TextField(default='Deploy and scale your automated workflows instantly', help_text='Step 3 description'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_3_title',
            field=models.CharField(default='Automate', help_text='Step 3 title', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_4_description',
            field=models.TextField(default='Grow your operations without technical limitations', help_text='Step 4 description'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='step_4_title',
            field=models.CharField(default='Scale', help_text='Step 4 title', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='team_image',
            field=models.ImageField(blank=True, help_text='Team member profile image', null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='team_name',
            field=models.CharField(default='Team floneo', max_length=100),
        ),
        migrations.AddField(
            model_name='architectingexcellencesection',
            name='team_role',
            field=models.CharField(default='CCO & Co-Founder', max_length=100),
        ),
        migrations.AlterField(
            model_name='architectingexcellencesection',
            name='subtitle',
            field=models.TextField(default="Together, we're creating a seamless experience that puts you in charge of your operations without IT bottlenecks.", help_text='Main subtitle/description'),
        ),
    ]
