# Generated by Django 5.0.1 on 2025-10-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_architectingexcellencesection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttabletsection',
            name='video_autoplay',
            field=models.BooleanField(default=True, help_text='Enable video autoplay'),
        ),
        migrations.AddField(
            model_name='abouttabletsection',
            name='video_controls',
            field=models.BooleanField(default=False, help_text='Show video controls'),
        ),
        migrations.AddField(
            model_name='abouttabletsection',
            name='video_loop',
            field=models.BooleanField(default=True, help_text='Enable video looping'),
        ),
        migrations.AddField(
            model_name='abouttabletsection',
            name='video_muted',
            field=models.BooleanField(default=False, help_text='Mute video by default (False = unmuted)'),
        ),
    ]
