# Generated by Django 5.0.1 on 2025-10-12 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_video_player_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person submitting the form', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the person submitting the form', max_length=254)),
                ('company', models.CharField(blank=True, help_text='Company name (optional)', max_length=255, null=True)),
                ('message', models.TextField(help_text='Message content from the contact form')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the form was submitted')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read/unread')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this submission', null=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
