# Generated by Django 5.0.1 on 2025-10-12 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('content', ckeditor.fields.RichTextField(default='\n        <h2>Information We Collect</h2>\n        <p>We collect information you provide directly to us, such as when you create an account, use our services, or contact us.</p>\n\n        <h2>How We Use Your Information</h2>\n        <p>We use the information we collect to provide, maintain, and improve our services.</p>\n\n        <h2>Information Sharing</h2>\n        <p>We do not sell, trade, or otherwise transfer your personal information to third parties without your consent.</p>\n\n        <h2>Data Security</h2>\n        <p>We implement appropriate security measures to protect your personal information.</p>\n\n        <h2>Contact Us</h2>\n        <p>If you have any questions about this Privacy Policy, please contact us.</p>\n        ', help_text='Privacy policy content (supports HTML formatting)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the privacy policy was last updated')),
                ('effective_date', models.DateField(help_text='When this privacy policy became effective')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this privacy policy is currently active')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (leave blank to use title)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
    ]
