# Generated by Django 5.0.1 on 2025-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with country code (e.g., +1 555-123-4567)', max_length=20, null=True),
        ),
    ]
