# Generated by Django 5.1.7 on 2025-12-05 08:02

import ckeditor_uploader.fields
import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_contactsubmission_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Technology, Business)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('color', colorfield.fields.ColorField(default='#3B82F6', help_text='Color for category display', image_field=None, max_length=25, samples=None)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this category')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g., automation, workflow)', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary of the blog post', max_length=300)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Main blog post content with rich text editor')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog/images/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (for accessibility)', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video URL')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file directly', null=True, upload_to='blog/videos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was published (auto-set when status changes to published)', null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars, defaults to post title)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes (auto-calculated)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on homepage')),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow comments on this post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Blog post author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Primary category for this post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for this post', to='content.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='content_blo_status_e01a49_idx'), models.Index(fields=['category', 'status'], name='content_blo_categor_42fc88_idx'), models.Index(fields=['slug'], name='content_blo_slug_441465_idx')],
            },
        ),
    ]
