# Generated by Django 6.0.2 on 2026-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_blogcategory_blogtag_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the user subscribed')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the subscriber', null=True)),
                ('source', models.CharField(default='blog_page', help_text='Where the subscription came from', max_length=50)),
                ('unsubscribe_token', models.CharField(blank=True, help_text='Token for unsubscribe link', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
