# Generated by Django 6.0.2 on 2026-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Optional badge label (e.g., 'New')", max_length=20),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='nav_type',
            field=models.CharField(choices=[('normal', 'Normal Link'), ('blog', 'Blog / Secondary Button'), ('cta', 'CTA Primary Button')], default='normal', help_text="'normal' = plain link in center, 'blog' = secondary button on right, 'cta' = NOT USED (Contact Sales is hardcoded)", max_length=10),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, help_text='Open link in a new browser tab'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='href',
            field=models.CharField(help_text="URL or anchor link (e.g., '#features', '/about', '/blogs')", max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='label',
            field=models.CharField(help_text='Text displayed in the navbar', max_length=50),
        ),
    ]
