# Generated by Django 6.0.2 on 2026-05-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_add_nav_type_fields_to_navigationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_1_description',
            field=models.CharField(default='Faster Application Development', max_length=200),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_1_value',
            field=models.CharField(default='40–60%', help_text='e.g. 40–60% or Enterprise-Ready', max_length=50),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_2_description',
            field=models.CharField(default='Lower Learning Curve', max_length=200),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_2_value',
            field=models.CharField(default='70%', help_text='e.g. 70% or 2.3x', max_length=50),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_3_description',
            field=models.CharField(default='by Design', max_length=200),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_3_value',
            field=models.CharField(default='Enterprise-Ready', help_text='e.g. 24/7 or Enterprise-Ready', max_length=50),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_4_description',
            field=models.CharField(default='Reduction in Development Costs', max_length=200),
        ),
        migrations.AddField(
            model_name='aipoweredanalyticssection',
            name='metric_4_value',
            field=models.CharField(default='Up to 50%', help_text='e.g. Up to 50% or 99.9%', max_length=50),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('orange', 'Orange'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('red', 'Red')], default='green', help_text='Icon background color', max_length=20),
        ),
        migrations.AlterField(
            model_name='aipoweredanalyticssection',
            name='feature_1_description',
            field=models.TextField(default='Accelerate delivery by replacing repetitive coding with visual workflows and reusable components.'),
        ),
        migrations.AlterField(
            model_name='aipoweredanalyticssection',
            name='feature_1_title',
            field=models.CharField(default='Development Speed', max_length=100),
        ),
        migrations.AlterField(
            model_name='aipoweredanalyticssection',
            name='feature_2_description',
            field=models.TextField(default='Build applications that scale securely without re-architecture or system rewrites.'),
        ),
        migrations.AlterField(
            model_name='aipoweredanalyticssection',
            name='feature_2_title',
            field=models.CharField(default='Scalability & Governance', max_length=100),
        ),
        migrations.AlterField(
            model_name='aipoweredanalyticssection',
            name='feature_3_description',
            field=models.TextField(default='Reduce engineering overhead, maintenance effort, and long-term technical debt.'),
        ),
        migrations.AlterField(
            model_name='aipoweredanalyticssection',
            name='feature_3_title',
            field=models.CharField(default='Cost Efficiency', max_length=100),
        ),
    ]
