# Generated by Django 6.0.2 on 2026-05-15 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_add_benefit_color_and_ai_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name displayed on the site', max_length=200)),
                ('website', models.URLField(help_text='Full URL (e.g., https://example.com)')),
                ('industry', models.CharField(default='Technology', help_text='e.g., Technology Solutions, Finance, Manufacturing', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of the client (1-2 sentences)')),
                ('logo', models.ImageField(blank=True, help_text='Upload the client logo image', null=True, upload_to='clients/')),
                ('accent_color', models.CharField(default='#0066FF', help_text='Hex colour used for card accent (e.g., #0066FF)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this client on the website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = shown first)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order', 'name'],
            },
        ),
    ]
