# Generated by Django 5.1.5 on 2026-05-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_add_client_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional image shown inside the blog post', upload_to='blog/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Optional caption displayed below the image', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order inside the blog post')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this image on the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(help_text='Blog post this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['blog_post', 'is_active', 'order'], name='content_blo_blog_po_6ab59a_idx')],
            },
        ),
    ]
